name: property_management_system
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  sqflite: ^2.0.2
  shared_preferences: ^2.0.13
  google_maps_flutter: ^2.1.3
  geolocator: ^8.2.0
  font_awesome_flutter: ^10.1.0
  flutter_custom_clippers: ^2.0.0
  flutter_svg_provider: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: ACaslonPro Bold
      fonts:
        - asset: assets/fonts/ACaslonPro-boldItalic.otf
          style: italic
    - family: ACaslonPro Regular
      fonts:
        - asset: assets/fonts/ACaslonPro-Regular.otf